// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ccl_borders
arma::mat ccl_borders(const arma::mat& m);
RcppExport SEXP ccloutline_ccl_borders(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    __result = Rcpp::wrap(ccl_borders(m));
    return __result;
END_RCPP
}
// ccl_outlines
Rcpp::List ccl_outlines(const arma::mat& m, const bool min_first);
RcppExport SEXP ccloutline_ccl_outlines(SEXP mSEXP, SEXP min_firstSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const bool >::type min_first(min_firstSEXP);
    __result = Rcpp::wrap(ccl_outlines(m, min_first));
    return __result;
END_RCPP
}
// ccl_cycles
Rcpp::List ccl_cycles(const arma::mat& m, bool reverse);
RcppExport SEXP ccloutline_ccl_cycles(SEXP mSEXP, SEXP reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    Rcpp::traits::input_parameter< bool >::type reverse(reverseSEXP);
    __result = Rcpp::wrap(ccl_cycles(m, reverse));
    return __result;
END_RCPP
}
// ccl_edges
Rcpp::List ccl_edges(const arma::mat& m);
RcppExport SEXP ccloutline_ccl_edges(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    __result = Rcpp::wrap(ccl_edges(m));
    return __result;
END_RCPP
}
// ccl_profile
Rcpp::List ccl_profile(arma::mat input, bool reverse);
RcppExport SEXP ccloutline_ccl_profile(SEXP inputSEXP, SEXP reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type input(inputSEXP);
    Rcpp::traits::input_parameter< bool >::type reverse(reverseSEXP);
    __result = Rcpp::wrap(ccl_profile(input, reverse));
    return __result;
END_RCPP
}
// ccl_labels
Rcpp::List ccl_labels(const arma::mat& m);
RcppExport SEXP ccloutline_ccl_labels(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    __result = Rcpp::wrap(ccl_labels(m));
    return __result;
END_RCPP
}
// ccl_paths
Rcpp::List ccl_paths(const arma::mat& m, const bool reverse);
RcppExport SEXP ccloutline_ccl_paths(SEXP mSEXP, SEXP reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const bool >::type reverse(reverseSEXP);
    __result = Rcpp::wrap(ccl_paths(m, reverse));
    return __result;
END_RCPP
}
